project:
  type: website
  output-dir: docs

website:
  title: "Food Process Design & Optimisation"
  page-footer: "Copyright 2023, Shane Crowley" 
  reader-mode: false
  page-navigation: true
  sidebar:
    style: 'floating'
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
      - section: "Food Physics"
        contents:
          - notes/quantities.qmd 
      - section: "Fluid Statics"
        contents:
          - notes/stokes-law.qmd
          - notes/pressure1.qmd
          - notes/pressure2.qmd
      - section: "Fluid Dynamics"
        contents:
          - notes/viscosity.qmd
          - notes/flow1.qmd
          - notes/flow2.qmd
      - section: "Separation Science"
        contents:
          - notes/evaporation-distillation.qmd
          - notes/membranes.qmd
          - notes/coffee.qmd
      # - section: "Powders"
      #   contents:
      #     - notes/concentration.qmd
      #     - notes/drying.qmd
      # - section: "Bulk Solids Science"
      #   contents:
      #     - notes/powder-technology.qmd
      #     - notes/flowability.qmd
      # - section: "Bulk Solids Science"
      #   contents:
      #     - notes/powder-technology.qmd
      #     - notes/flowability.qmd
      # - section: "Integrated Processes"
      #   contents:
      #     - notes/process-flow.qmd
      #     - notes/formulation.qmd
      # - section: "Sustainable processing"
      #   contents:
      #     - notes/concept.qmd
      #     - notes/implementation.qmd
      # - section: "Advanced Topics"
      #   contents:
      #     - notes/digestion.qmd
      #     - notes/scale.qmd
      - section: "Appendix"
        contents:
          - notes/slides.qmd
          # - notes/review.qmd
          # - notes/reflections.qmd
          # - notes/interactions.qmd
          # - notes/syllabus.qmd
      # - notes/about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/edibotopic/foodPro
          - text: Report a Bug
            url: https://github.com/edibotopic/foodPro/issues


format:
  html:
    theme: 
      light: [theme.scss]
      dark: [superhero]
