project:
  type: website
  output-dir: docs

website:
  title: "Food Pro"
  page-footer: "Copyright 2023, Shane Crowley" 
  reader-mode: false
  repo-url: https://github.com/edibotopic/foodPro
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    style: 'floating'
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
      - section: "Food Physics"
        contents:
          - notes/quantities.qmd 
      - section: "Fluid Statics"
        contents:
          - notes/stokes-law.qmd
          - notes/pressure1.qmd
          - notes/pressure2.qmd
      - section: "Fluid Dynamics"
        contents:
          - notes/viscosity.qmd
          - notes/flow1.qmd
          - notes/flow2.qmd
      - section: "Separation Science"
        contents:
          - notes/evaporation-distillation.qmd
          - notes/membranes.qmd
          - notes/coffee.qmd
      - section: "Powders"
        contents:
          - notes/concentration-drying.qmd
          - notes/bulksolids.qmd
          - notes/mixing.qmd
            # - section: "Appendix"
            # contents:
            # - notes/slides.qmd
      # - about.qmd
format:
  html:
    theme: 
      light: [theme.scss]
      dark: [superhero]
    toc: true
