---
title: Concentration and Drying
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
---
---

Concentration refers to an operation where water is removed to concentrate solids.
*Solids* usually refers to any components that are not water.
Thus, concentration involves no fractionation of components in the solids, meaning there is not change in the relative proportion of protein and sugar, for example.
There are several advantages to concentration, including:

- Reduced weight due to water removal
- Decreased microbial growth due to lower water content/activity

In addition, concentration is commonly applied to liquid systems prior to operations like spray-drying, due to the energy efficiency of the concentration operations.

## Evaporation

Evaporation usually refers to a phase change ($liquid \to vapour$) that occurs when the temperature of a liquid is increased above its boiling point ($T_B$).

::: {.callout-note}

Scientists often distinguish between evaporation and boiling as two distinct types of **vapourisation**, where evaporation can occur at temperatures below boiling temperature (think of a water puddle that dries out on a cold Irish day) and involves generation of vapour at the liquid surface, while boiling occurs at or above boiling temperature (water in a kettle) and involves generation of vapour throughout the bulk of the liquid.

I am not convinced that this distinction is critical to understanding evaporation *as an operation*, so I will typically use "evaporation" to refer to the generation of vapour.
You are free to explore the technical distinction further if you wish.

:::

$T_B = 100 °C$ for water in normal atmospheric pressure.
Even at room temperature, some water molecules gain sufficient energy to become vapour but they are very few in number.
As temperature increases, and approaches $T_B$, the number of water molecules entering the vapour phase increases, resulting in a progressively greater *vapour pressure*.
You can imagine the vapour pressure ($T_V$) as being opposed by the atmospheric pressure — as the vapour pressure increases from a small value (at 20 °C) to a big value (at 100 °C), evaporation is able to proceed more rapidly as the vapour mor easily overcomes the atmospheric pressure.
When $T_V$ exceeds (or equals) $T_B$ then boiling occurs, resulting in rapid vapourisation.

An evaporator is a machine designed to promote the evaporation of a liquid with dissolved solids (i.e., dissolved substances) so that it becomes more concentrated.
In food processing **evaporation** often refers to an *operation* in which an evaporator is used to concentrate a liquid food or beverage (*via* the mechanism of evaporation).

By *more concentrated* we mean **more concentrated in solids (everything that is not water)**.

::: {.callout-warning}

Technically, both evaporators and driers involve the phase change of evaporation (as does other operations such as distillation).

A way to distinguish them is to remember that an evaporator does not change the form of its input.
So while a spray-drier transforms a liquid into a powder, an evaporator merely changes the properties of a liquid — the liquids become more concentrated

As we will see, they are frequently used together.
:::

A simple evaporator would consist of an open tank heated to a high temperature (at or approaching boiling temperature).
There are several reasons why this would be a bad approach, however, due to the high temperatures involved:

1. Nutrients may become degraded
2. Energy costs will likely be high
3. Undesirable chemical changes may occur

For these and other reasons, a specific evaporator design — the *multi-effect falling-film evaporator* — is common.

::: {.callout-important}

## The Story of How the Evaporator was Invented

If you benefit from human interest stories when learning technical material I would recommend the tale of how [Norbert Rilliuex](https://www.acs.org/content/acs/en/education/whatischemistry/landmarks/norbertrillieux.html#multiple-effect-evaporator) developed the multi-effect evaporator technology that is largely still in use today.

:::

## Evaporator Design

The evaporator has several important design features that allow it to work effectively.
The multiple "effects" refer to **stages** where the evaporation will occur.
Each stage consists of an enclosed chamber containing a series of tall, **vertical tubes**.
The liquid to be concentrated falls down the inner walls of these tubes as a film.
In the first stage **steam** is pumped into the shell that surrounds the tubes, heating the film through the walls of the tubes.
A **vacuum** pump is used to reduce pressure in each effect (a partial vacuum is created, removing air molecules that would otherwise oppose vapour pressure), meaning that the boiling temperature of the liquid is reduced.
In the first stage, the concentrate is separated from the vapour, both are then passed into the second stage, which operates at a **lower pressure** than the first — at this lower pressure the vapour can act as the heating medium, promoting the evaporation of more water from the concentrate.
This process can be repeated across up to seven stages, with pressure decreasing at each successive stage as the liquid becomes more concentrated and the vapour is continuously recycled to use as the heating medium (instead of steam).
Vapour is collected at the end of the operation and cooled into liquid water by a **condenser** — this water can then be used to generate steam to initiate the evaporation process again.

To summarise:

### Vacuum

A vacuum is pulled in the evaporator to reduce the boiling point of the liquid.
This means that temperatures as low as 60-70 °C can be used to generate vapour rather than the more severe 100°C.

### Effects

"Effects" refer to stages in the evaporator where the liquid is concentrated, and in each stage there is some vapour removed.
The liquid becomes more concentrated with each stage making it more difficult to evaporate water using hot vapour.
For this reason, the pressure is reduced in each successive stage.
There can be up to seven effects in a commercial evaporator — the more effects that are used the greater the efficiency because more vapour (from the product) can be used as heating medium (instead of steam).
This efficiency is an investment, as more effects increase capital costs.

### Films

Liquid is pumped to the top of the evaporator.
From there, the liquid falls as a film down the inner walls of a long, vertical tube.
The liquid is heated by steam circulating outside of the tube.
As the liquid falls by gravity the vapour generated separates from the liquid.
In most evaporators each stage consists of a large number of these tubes.

### Condenser

Vapour can be turned back into liquid water by a condenser.
This water can then be used (boiled) to generate steam that can be used in the evaporation process.

## Applications and Issues

Evaporators can be used to make liquid, concentrated products like evaporated juices and milk.
As they are highly energy-efficient, they are often used in conjunction with more energy-intensive driers.

During evaporation, the concentration of solids increases, which causes an increase in viscosity.
This may also cause some molecules to be pushed passed their solubility limit.
The combination of high viscosity and reduced solubility can occsionally cause fouling issues (build up of deposits in evaporator tubes).
For example, in whey systems calcium phosphate may begin to precipitate, which is exacerbated by the fact that calcium phosphate is less soluble in warm temperatures.

## Alternatives to Evaporation

There are non-thermal alternatives to evaporation that can remove water.

Many of these are based on membrane filtration; for example, Reverse Osmosis involves the use of membranes that have pores that only allow the permeation of water (allowing the removal of water as solids are concentrated).

The name "Reverse Osmosis" distinguishes it from the phenomenon of Osmosis.
Osmosis occurs when on one side of a membrane there is a high concentration of osmotically-active substances and on the other there is a low concentration.
Common dissolved solids (or "solutes"), like salts, sugars and proteins, are osmotically-active.
For example, when vegetables are added to a salty brine the high concentration of salt results in water moving (via osmosis) from the inside of cell membranes to the brine, resulting in a characteristic "pickling" effect.
In membrane-based concentration the opposite (or reverse) goal is pursued — water must be removed from the solution containing osmotically-active components (salts, sugars, proteins, etc.).
To achieve this pumps and valves are used to increase pressure on the concentrate side, overcoming osmosis.

- Osmosis: water flows from region of low solute concentration to high solute concentration due to natural osmotic pressure differences
- Reverse osmosis: water flows from region of high solute concentration to low solute concentration due to pressures induced by pumps and valves

Reverse Osmosis may be favoured because it can be operated at even lower temperatures than vacuum evaporation (refrigeration to room temperature); however, membrane filtration processes are severely limited by viscosity development when concentration increases.
This means that solid concentrations of 20-25% solids may be possible with reverse osmosis, but this may need to be supplemented with evaporation to achieve higher concentrations (40-60% solids).

## Drying

Drying involves a substantial removal of water from a food.
While evaporation can increase the solids of a liquid feed to 50-60%, drying can achieve further increases to 90-95%.
In other words, a powder will typically have a final moisture content of approximately 5-10%.

The drying of food products results in a significant increase in shelf-life and a range of other practical benefits, including reduced weight, which reduces transit requirements.
For export-led food industries — like Ireland's — the powder format is a critical output.
While you might be familiar with powders from the supermarket (e.g., milk powder, cocoa powder), massive quantities of powder are also traded between companies; for example, one company might supply cocoa powder to a second who uses it to make cake products.

## Dried Foods and Powders

Drying yields a low-moisture product.
The reduction in moisture is so significant that the structure of the food is typically altered.
For example, raisins do not resemble the grapes they are dried from and present a very different sensory experience.
That drying results in such a transformation in structure can be considered a distinguishing feature relative to the operation of evaporation.

Dried foods like powders are inherently flexible, in that it is trivial for the user to alter concentration.
For example, while milk contains protein it is difficult to use milk as a method of increasing the protein content of a food, because the addition of milk introduces a substantial quantity of water also.
On the other hand, addition of milk powder can dramatically alter the protein content (and sugar content) of a product by varying its addition levels.

## Water Activity

Most scientists do not consider drying to succeed as a method of shelf-life control due to its reduction in moisture content, but rather due to its reduction in water activity ($a_w$).
Informally, water in a food system can be considered as either *free* or *bound*.
Free water is equivalent to the pure water found in a glass and is expected to exert the same vapor pressure as that pure water.
Bound water — on the other hand — is tightly associated with other food components (like proteins), which makes those bound water molecules less likely to vaporise (and thereby contribute to vapor pressure).

As a general observation then, pure water has a high vapor pressure while food systems have a relatively low vapor pressure; however, different food systems will have dramatically different vapor pressures, some close to water and some far from water.
Water activity can then be defined based on vapor pressure ($V_p$) as:

$$a_w = \frac{V_p \ of \ food}{V_p \ of \ pure \ water}$$

with:

$$0 < a_w < 1$$

The drying of food can significantly reduce water activity (bring $a_w$ closer to zero, which improves shelf-life).
This can be thought of as reducing the amount of free water that would otherwise be available to support undesirable events, such as microbial growth and chemical changes.

For example, fresh meat has a water activity of 0.99 (close to water) while beef jerky has a value of <0.80.
Liquid milk has a value of ~0.99 while milk powder has a value of <0.30.
Water activity is a more reliable predictor of shelf-life than moisture content and it is known that some foods with the same moisture content can have dramatically different shelf-lives, due to their differing water activities.

In general, the rates of reactions and the extent of microbial growth increase with increasing water activity.
It is also well known, however, that there are thresholds of water activity beyond which certain reactions or bacterial growth occur to a negligible degree.
For example, there is limited bacterial growth when water activity is maintained below 0.9, while molds will not grow below 0.7.
Notably, however, some chemical reactions can still proceed at very low water activity, such as browning (>0.2).

A hygienically-produced powder then, with a water activity at least as low as 0.3, is far below the level where the growth of microorganisms can be expected; however, two important things should be noted at this point:

1. Powders can still exhibit significant chemical changes during storage
2. Powder prone to absorbing moisture from the air (e.g., high sugar) can exhibit increased water activity over time

Despite these caveats, a well-manufactured powder should have a shelf-life of 12-24 months, especially if carefully packaged and stored.

## Spray-drying

Some industrial drying systems resemble a common kitchen oven.
The *tray drier* consists of heating elements, fans, food trays and an exhaust.
The fan draws air into the drier, with the air being heated by the elements, before passing over the food, initiating evaporation of moisture.
Moist vapor is then removed in the exhaust.
Such systems can be augmented to optimise drying performance; for example, a vacuum pump can be used to reduce pressure in the drier and thereby decrease the temperatures the food needs to be expose to in order for drying to occur.
Such a system is a batch method of drying and is not suitable for liquids.

For the continuous drying of liquid feeds the spray-drier is common.
A spray drier consists of a large cylindrical chamber that tapers into a conical section at the bottom.
Feed (typically concentrated feed from an evaporator) is pumped to the top of the vessel and through a nozzle.
As the liquid passes through the nozzle it is transformed into a fine mist.
This phenomenon is known as "atomisation" and dramatically increases the surface area of the material to be dried.
Hot air is simultaneously fed into the chamber, and the high temperature difference between the liquid and the air,
combined with the large surface area of the droplets, results in rapid evaporation.

The exact temperatures vary according to the processor and the product, but generally the temperature of air at the inlet of the drier can be as high as 130°C, while the temperature at the outlet can be as low as 65°C.
This difference reflects the impact of evaporative cooling, which occurs when heat energy contained in liquid water is lost in the vapor during evaporation.
The impact of evaporative cooling also means — importantly — that the liquid being dried does not itself reach temperatures approaching the inlet temperature (which could cause significant quality degradation); in this regard, the outlet temperature (a much lower value) is more reflective of the moderate temperatures to which the components in the liquid are exposed.

The powder and exhaust typically pass into a cyclone where the (heavy) powder is separated from the (light) exhaust.
In the exhaust will be entrained "fines", which are tiny powder particles. These fine particles may be recycled back into the drier (known as "fines return") to achieve agglomeration of particles — this works by forcing collisions between fine dry particles and wet atomised droplets, which results in the formation of clusters (or "agglomerates") that are dried into large porous particles (usually with better functionality).

## Powder Functionality

In most cases (there are some exceptions) powders are expected to be soluble.
In addition, they are expected to flow easily out of containers and to be stable/useable for extended periods.

Unfortunately, these quality criteria are not always met and are the subject of continued research that aims to ensure that quality standards are maintained, especially in more recently-developed powders (e.g., new protein isolates).

The composition of a powder can affect its functionality, with high fat powders tending to be more sticky.
Furthermore, if a powder tends to absorb moisture from the air, then that powder can also become sticky over time.

Designing spray-driers to achieve agglomeration, which can involve "fines return" (described above), which increases both the size and porosity of powders, is a common strategy to improve both solubility and flowability.
