---
title: Flow
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: false
---
---

::: {.callout-warning}

These notes are written to accompany the lectures, not to replace them.

:::

# Flow

Processes consist of a series of operations, each with an input and output.
Materials flow between operations, and in modern food factories this flow is often continuous.
A high rate of flow is often desired because it ensures a process is efficient (ratio of value flow out to value flow in).
Changes in flow-rate — especially decreases — often indicate a problem, such as equipment blockage or material supply issues.
The flow of food liquids is complex and involves an interplay between equipment properties (pipe geometry), food characteristics (viscosity) and flow behaviour (turbulence).
Carefully controlling these factors can allow effective operations like homogenisation to be designed.

## Quantities

There some quantities that are used to define flow that are important to remember.
Please review the equations outlined below and try to understand them.
The mathematics and physics knowledge required is not advanced (where it is this is indicated).

### Volumetric Flow-rate

Flow-rate for liquids is usually given the symbol $Q$ and is defined as:

$$Q = \frac{V}{t}$$

The units are most commonly $L \ h^{-1}$ or $m^3 \ h^{-1}$.

::: {.callout-note}

Writing $L \ h^{-1}$ is equivalent to $L/h$.

Similarly, $m \ s^{-2}$ — the units of acceleration — can also be written $m/s^{2}$.

Do not let the exponents and negative numbers confuse youa and rewrite them if it helps.

:::

A common method of measuring flow-rate in a lab is to periodically measure the volume collected over a certain period of time.
For example, if 300 mL is collected from a pipe in 30 seconds we could convert this to a flow-rate by first converting mL → L:

$$\frac{300}{1000} = 0.3 \ L$$

This means that 0.3 L is collected per 30 s, but we need the volume in an hour, so we do the following:

$$0.3 \times 2 \times 60 = 36 \ L \ h^{-1}$$

This quantity is known sometimes as the "volumetric flow-rate".
If units for mass (e.g., kg) are used instead then it "mass flow rate".

### Velocity of flow

The volumetric flow-rate ($Q$) has the units $m^3 \ s^{-1}$.

We know that a common way of expressing velocity is meters-per-second.
From the units above we can expect that to calculate velocity of flow we simply divide $Q$ by an area $A$:

::: {.callout}
Why can we "expect" this? Because to convert $m^3$ to $m$ (or $m^1$) we need to divide by $m^2$, when these values are divided the exponents subtract like so: $\frac{m^3}{m^2} = m^{3-2} = m^1 = m$.
:::

$$v = \frac{Q}{A}$$

The area in this case is the cross-sectional area of flow.
In food engineering calculations this is nearly always the area of a disc (because we are usually dealing with pipes).

The velocity is often required in equations where the flow-rate cannot be used (you need to understand that they are different).
For example, the Reynold's number used to define turbulence uses velocity not flow-rate.

Velocity is a `vector` quantity, so to be more precise we could write $\overrightarrow{v}$.
It also represents an `average` value, meaning that it represents the statistical average of a range of individual velocities.
How this is normally represented is that a fluid moving through a pipe consists of `stream-lines`, each flowing in a specific direction.
In `laminar` (non-turbulent) flow the maximum velocity is in the centre and the velocity at the edges is $0$.
This means that liquids flows in a "curved" fashion, with the fastest streamlines in the centre.

## Velocity, Pipe Area and Pressure

We all know intuitively that what flows into a system must flow out.
If you pour some water into a tank and add two fish, you would expect to recover the same quantity of each when the tank is drained.

This can be summarised in the following equation:

$$Q_{in} = Q_{out}$$

This is important but unremarkable.
We also know, however, that:

$$v = \frac{Q}{A}$$

or:

$$Q = v \cdot A$$

Therefore:

$$v_{in} \cdot A_{in} = v_{out} \cdot A_{out}$$

If we re-arrange to solve for $v_{out}$ we get an odd result:

$$v_{out} = \frac{v_{in} \cdot A_{in}}{A_{out}}$$

It is perhaps more obvious when the formula is represented as:

$$v_{out} = v_{in} \cdot \frac{A_{in}}{A_{out}}$$

This means that the velocity in a pipe increases when the pipe narrows.
A second important effect during this narrowing is that pressure decreases (a derivation for this is included below but is only for those who want a deeper understanding).


::: {.callout-tip}
These two effects will later be used to explain how a homogeniser works.

So take a note and don't forget to make the connection.

:::

::: {.callout-important}

## Explanation for Pressure Drop with High Velocity (advanced topic)

The explanation for why pressure decreases when a pipe narrows is more complex.
Bernoulli's equation is usually used to describe the balance of pressures between two regions of pipe:

$$\frac{P_1}{\rho g} + \frac{v_1^2}{2g} + h_1 = \frac{P_2}{\rho g} + \frac{v_2^2}{2g} + h_2$$

On each side, the term with $P$ can be taken to mean "pressure", $v$ velocity and $h$ height.
In the systems discussed in the lecture there is no difference in height between the two regions.
In addition, the velocity in the narrow region is very high relative to the wider region.
For these reasons, we can remove the height terms (they are equal) and also the $v_1^2$ (a tiny value).

$$\frac{P_1}{\rho g} = \frac{P_2}{\rho g} + \frac{v_2^2}{2g}$$

To simplify we can bring the pressure term from the right to the left.
As the pressure term from the right now subtracts from the left we can represent it as a pressure difference ($\Delta P$):

$$\frac{\Delta P}{\rho g} =  \frac{v_2^2}{2g}$$

To isolate the $v_2^2$ we can multiple by $2g$ on both sides, which has the effect of cancelling the $g$ on the left:

$$\frac{2 \Delta P}{\rho} =  v_2^2$$

To simplify further we can take the square root of both sides:

$$v_2 = \sqrt{\frac{2 \Delta P}{\rho}}$$

Note: this implies that as we increase velocity (i.e., due to a narrowing in pipe area) there is also an increase in pressure drop (due a loss of pressure in the narrow region).
This has been experimentally determined to be correct.
:::

## Viscosity

Informally, viscosity is a measure of the resistance of a liquid to flow.
It is a critical property in food that is important both in processing behaviour and in consumer acceptance.

Viscosity is defined as the ratio of the deformation stress applied to a liquid and the extent of the resultant deformation.
More formally, it is the ratio of shear stress to shear rate.
A viscous liquid requires more shear to cause deformation or flow.

For liquids to flow during food processing the viscosity of the liquid and the friction between the liquid and the equipment must be overcome.
Liquids must be pressured using pumps to create a sufficient pressure drop across a pipe to ensure consistent flow of material.

::: {.callout-tip}

## The Easiest Way to Understand Viscosity?

Perhaps the easiest way to measure and understand viscosity is the **falling ball**.
Another advantage of thinking about viscosity this way is that it can be helpful to remember how emulsions and suspensions behave.

---

[Simulation to "re-discover" the equation that describes floating/sinking velocity](https://edibotopic.github.io/stokes-law/)

---

The velocity of a falling ball in a liquid is given by (note — *there must be a density difference*):

$$v = \frac{D^2 \cdot (\rho_{ball} - \rho_{liquid}) \cdot g }{18 \cdot \mu}$$

As viscosity ($\mu$) is below the line, this means that its increase results in a decrease in velocity — more viscous liquids create more *drag* on objects.
One of the easiest and cheapest ways to measure viscosity is to take a ball of known dimensions (diameter, density) and place it in a liquid of known density.
The time it takes for the ball to sink a certain number of centimeters can then be used to calculate velocity, which means we know every value in the equation except for viscosity.
Re-arranging the equation allows us to solve for this value:

$$\mu = \frac{D^2 \cdot (\rho_{ball} - \rho_{liquid}) \cdot g }{18 \cdot v}$$

**Note: that diameter is squared in the equation is very important, and means that reducing the diameter of a particle or droplet (for example: by homogenisation) has a massive effect on its separation velocity.**

:::

The science of viscosity is complex and it is not the purpose of this module to explain it in detail.
For now, consider some *general* facts about viscosity in a food context:

- Viscosity tends to decrease with increasing temperature unless some transformation occurs (i.e., if a protein solution is heated until the proteins denature then viscosity is likely to increase)
- Many (not all) liquids in food processing tend to be shear-thinning (i.e., products like yogurt and ketchup tend to becomes more liquid-like the more stress that is applied)
- Some liquids are "ideal" meaning there is a linear relationship between stress and deformation (e.g., liquids like oil, water and syrups generally deform to the same extent no matter how much force is applied)

## Turbulence

Viscosity opposes the effects of turbulence during food processing.
Turbulence represents phenomena associated with the chaotic motion of fluids.

A high degree of turbulence is often desirable in many food operations, such as heating and mixing.
Turbulence is calculated from a famous equation that returns the Re(ynold's) number:

$$Re = \frac{v \rho D}{\mu}$$

Note that viscosity is below the line, meaning that a lower degree of turbulence is often observed in viscous systems.

For our purposes it might be sufficient to remember that turbulence is proportional to velocity (it increases when velocity increases):

$$Re ∝ v$$

and inversely proportional to viscosity (it decreases when viscosity increases):

$$Re ∝ \frac{1}{\mu}$$

When a liquid is pumped at a high velocity it is more likely to transition into chaotic motion, which can be preferable in specific situations:

- Turbulence can decrease the tendency for particles to form deposits on equipment surfaces
- Turbulence can increase the rate of heat transfer during thermal processing
- Turbulence can promote the disintegration of particles

This last point helps explain the operation of a homogeniser.

## Homogenisation

A homogeniser is a piece of equipment that can be used to continuously reduce the size of solid particles or liquid droplets in a mixture.

Its working principles is based on concepts encountered in previous sections (mainly *the influence of flow area on velocity and pressure*):

1. The liquid being pumped into a homogeniser is forced through a narrow orifice (or nozzle)
2. The decrease in flow area increases velocity and therefore turbulence
3. The decrease in velocity causes a pressure drop, which can cause cavitation
4. The chaotic motion, cavitation effects and high shear results in particle size reduction
5. Homogenisers are often operated at slightly elevated temperature to reduce the influence of viscosity

::: {.callout-note}

## Cavitation

At normal atmospheric pressure, when water is heated to 100 °C it boils.
Boiling results in the formation of vapour (phase transition between liquid and gas) evidenced by the appearance of bubbles that form and collapse.

A similar thing can happen when pressure drops while temperature is constant, which happens when liquid is accelerate to high velocities.
The boiling point of a liquid decreases as pressure decreases, meaning that it can begin boiling at lower temperatures than normal.

(We will see in the **concentration** section how reducing boiling point like this can be used to our advantage).

When cavitation occurs in food processes (such as homogenisation) it leads to the formation of vapor bubbles in the liquid, which then collapse under the pressure of the surrounding liquid, releasing thermal energy that can contribute to particle size reduction.

**If you want a colouful example to help understand this look up videos of the "pistol shrimp", a shrimp that attacks threats underwater with a high-speed motion that causes cavitation to occur, creating bubbles that implode and sometimes shatter the hard shells of unsuspecting creatures.**

:::

# Conclusions

- All food processes involve a flow of materials
- The flow-rate into an operation should equal the flow-rate out
- The efficiency of many operations is determined by the flow-rate it outputs
- Converting from flow-rate to flow velocity reveals interesting facts about flow behaviour
- In general, a narrowing of flow area results in an increase in velocity and a decrease in pressure
- Increases in velocity can cause turbulence and cavitation, which can have positive effects (such as in homogenisation)
- Viscosity opposes turbulence, which can reduce the effectiveness of operations like homogenisation 
- To overcome this, elevated temperature can be used to decrease viscosity


# Topics of Interest

We do not have time in this module to go into these in detail, but here are some interesting topics to reflect on:

- Many people must be tube-fed their food because of various health conditions, including some premature babies born with low birth weights. Tube-feeding — similarly to what is described above — requires continuously pumping material through tubes/pipes.
It has been shown that as much as 40% of the lipids in some of these tube feeds may never be delivered during these (apparently simple) tube-feeding operations for infants, which could have a significant effect on nutrient and calorie delivery.
This is likely causes by the instability of the fat droplets, which could form deposits during pumping.
- Some companies have marketed "unhomogenised milk" in response to market demand for minimally-processed products and the nostalgic associations some people have for unhomogenised milk that would be delivered on the doorstep in glass bottles.
In these campaigns, homogenisation is described as a "violent" operation that "damages"/"breaks" components in the food (implication: it does not just cause size reduction but something otherwise negative).
Other companies, particularly those with products stocked in alternative or healthfood stores, often market their physically unstable products in a positive way, by saying that it is a "natural" phenomenon due to their choice not to use homogenisation.
- Is homogenisation bad? Homogenisation is one of the simplest operations in the sense that it typically does not involve any major chemical changes (unlike thermal processes). In certain cases, like tube-feeding, unhomogenised products may simply *not work*.
However, some research has recently suggested that homogenisation changes the rate at which both lipids and proteins are digested.
The surface area of the fat is increased through homogenisation, which can accelerate digestion, but proteins are also dispersed across the surface of the fat, which has been linked with increased digestion rate of protein also.
Research in this area is in its early days, so it is difficult to draw definitive conclusions in terms of whether this is better or worse and in which circumstances it might matter.


**References available on request.**
