---
title: Membrane Filtration
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
---
---

Many raw materials in food processing are complex mixtures of many different components. 
For a variety of reasons, it is often desirable to concentrate or fractionate mixtures into sub-sets of their
components.
In dairy processing, for example, this is often practiced to create new ingredients.
These ingredients may have specific *bio-functional* (e.g., nutrition) or *techno-functional* (e.g.,
stabilisation) attributes that make them useful in applications.

A major issue affecting membrane processes in the food industry is *fouling*.
Fouling is simply to formation of a solid deposit on the membrane surface over time.
This can lead to several problems, including reduced flow-rates, altered membrane selectivity,
process shut-downs and increased cleaning requirements.

Membrane filtration is a large, complex area of study.
These notes and the associated lecture are only a brief introduction.

::: {.callout-tip}

## Fractionation and concentration

"Concentration" usually refers to a process by which all components of a certain class are recovered by a membrane.
For example, reverse osmosis of fruit juice is a concentration process in which all the solid components are recovered while the water is removed.
As another example, ultrafiltration of whey is a concentration process in which all of the protein is recovered while smaller molecules and water are removed.

"Fractionation" often refers to more subtle filtration processes in which components within a class might be separated.
For example, microfiltration can be used to separate proteins based on their molecular weights.

:::

## Types of filtration

### Dead-end

A distinction is usually made between "dead-end" and "cross-flow" filtration.
The former involves a type of filtration that is similar to the common use of filter paper in laboratories.
A feed material flows perpendicularly towards the filter surface, with some material being retained (e.g., crystals) and others permeating (e.g., water).
It is typically observed that this kind of filtration results in a rapid decline in permeation rate.
While this is a minor inconvenience in a laboratory, it can be a major problem at industrial scale.

The reason for the decline in permeation rate is a loss of pressure and membrane fouling.
Pressure ($P$) in such a system is given by $P = \rho g h$, where $h$ is the height of the liquid above the filter surface.
Fouling is simply the accumulation of retained components on the membrane surface, which increases resistance against the flow of permeate.
Common strategies to overcome these issues in a laboratory context might be:

- Adding more feed to the system (e.g., increasing pressure)
- Displacing the fouling deposits with a glass rod (e.g., increase shear near the membrane surface)
- Stopping the filtration and replacing the filter

### Cross-flow

Most membrane operations in industries like dairy involve cross-flow filtration.
In cross-flow filtration the feed liquid flows a**cross** or parallel to the membrane surface.
The feed then continuously removes fouling material from the membrane surface over time.
Generally, this gives far superior performance to dead-end flow; however, it is not perfect and gradual fouling is still a problem.

When attempting to develop strategies to maximise permeate flux it is useful to consider Darcy’s equation:

$$J = \frac{TMP}{\mu \cdot R}$$

$J$ signifies permeate flux (probably because $F$ is already taken for "force"), $TMP$ stands for **T**rans **M**embrane **P**ressure, $µ$ for permeate viscosity and $R$ for hydraulic resistance.
To generate permeate a pressure drop must exist from the feed-side to the permeate-side.
Pressure is supplied by a pump and through the closing of a valve on the retentate line.

For a filtration process to be productive and efficient it is typically preferable that permeate flux be *rapid* and *sustainable*.
Intuitively, reading the equation above, it would seem obvious that a high $TMP$ and a low *viscosity* would yield the best outcome in this regard.
The $R$ value can really be understood as the sum of two terms, one being the resistance due to the membrane and the other due to the fouling layer.
In obvious symbols this can be written:

$$R = R_m + R_f$$

To some extent, $R_m$ is outside of our control, as it depends on the conditions under which the membrane was manufactured and the type of membrane process we are running.
For example, in order of pore-size membrane processes fall into the following general categories:

::: {.callout}
microfiltration > ultrafiltration > nanofiltration > reverse osmosis
:::

Reverse osmosis (RO) involves the smallest pores, which only let water molecules through.
The pores in nanofiltration (NF) membranes are larger and allow the passage of monovalent ions as well as water.
Ultrafiltration (UF) lets sugars and divalent ions permeate, in addition to monovalents and water.
Microfiltration (MF) membranes can be selected to retain bacteria and/or fat and/or some proteins, while allowing smaller molecules permeate.

It should be obvious that the smaller the pore-size, the greater the resistance the membrane resists the flow of permeate.
This can be understood as one reason why the amount of pressure required for each category is in the order:

::: {.callout}
RO > NF > UF > MF
:::

NF processes will simply require greater pressures than MF processes, which is a limitation associated with the construction of the membrane itself.

What is under the control of the processor to a greater extent is resistance due to fouling and the viscosity of process fluid.

::: {.callout-note}
## MWCO

Within a specific membrane category, like UF, membranes can be purchased at different molecular-weight cut-off (MWCO) values.
MWCO determines which molecules will be blocked from passing through the membrane.
For example, in milk and whey the smallest protein is α−lactalbumin, which has a molecular weight (MW) of 14 kDa.
If the goal is to concentrate all protein the it is thus sufficient to select a MWCO that will ensure that this
smallest protein does not permeate, as it follows logically that the larger proteins will not permeate if this condition is met.
For this reason, UF of milk and whey is commonly performed using MWCOs of ~10 kDa.
:::


## Optimising for permeate flux 

Declines in flux during filtration are common and typically caused by
fouling of the membrane surface. The results in an increase in hydraulic
resistance ($R$ in Darcy’s equation).
Fouling is a complex phenomenon which can be simply understood as the deposition of molecules at the surface of
the membrane and, in some cases, inside the membrane pores themselves.
An advantage of cross-flow filtration is that the feed material moves across the membrane surface during pumping, which contributes to the continuous removal of the fouling layer during filtration - this is not perfect, however.

### Permeate viscosity

Most liquids decrease in viscosity as temperature increases.
This is true unless a qualitative change occurs, such as when proteins denature and aggregate to form larger structures that impart greater viscosity.
For these reasons a temperatures of approximately 40-60°C have been common for filtration processes in the dairy industry (not too low, not too high), for example.

Darcy's Law includes a viscosity parameter that refers to permeate viscosity.
The viscosity of permeate generated during filtration is typically low (similar to water).
However, minor changes in permeate viscosity associated with temperature can have a significant effect on permeate flux.

### Cross-flow, turbulence and retentate viscosity

In cross-flow filtration the feed flows parallel to the membrane surface, contributing to the removal of foulant.
However, the effectiveness of this cross-flow mechanism is dependent on the turbulence generated by the feed flow.
Turbulence is typically defined for pipes using the Re(ynold's) number:

$$Re = \frac{v \cdot D \cdot \rho}{\mu}$$

The higher the $Re$ the greater the turbulence.
Two important factors in this equation are velocity ($v$) and viscosity ($\mu$).
Turbulence is directly proportion to the former and inversely proportional to the latter.
In cross-flow filtration, maximising $v$ is achieved by ensuring a sufficiently high feed-flow rate is attained.

Retentate/feed viscosity can increase substantially during filtration due to an increased concentration of the feed.
The increased viscosity can reduce cross-flow velocity and turbulence of the feed, which can contribute to fouling.
Diafiltration — the addition of water to the feed during filtration — helps maintain a low viscosity.
For the production of high-protein materials like whey protein isolate using filtration diafiltration is necessary.

The use of feed spacers, mesh-like structures that disrupt flow and generate turbulence are also common in most miodern cross-flow filtration systems.

### Critical flux

From Darcy's Law it can be assume that $J$ increases linearly with $TMP$.
In reality, this is a simplification, and $J$ plateaus beyond a certain "critical flux".
This creates a distinction between the linear (pressure-dependent) and plateau (pressure-independent) regions.
The most severe fouling is associated the the pressure-independent region, which therefore should be avoided.

Ideally, the highest TMP should be chosen in the pressure-dependant region of the J−TMP curve; this means that if you adjusted the pressure in stepwise increments you would find a linear region that eventually transitions into a plateau — the idea is to select the TMP before that plateau is reached, as the plateau is associated with high degrees of fouling.
This requires a trade-off between short-term and long-term productivity, as the initial sacrifice in flux should pay off in longer run-times without requirements for process shutdown and cleaning.


### Anti-fouling technology

Membrane fouling is a continued problem in the food industry. 
Scientists and engineers are investigating multiple approaches to minimise
this phenomenon, such as:

- Optimising spacer mesh design to promote internal turbulence
- Fabrication and modification of membrane polymers to repel depositing molecules
- Use of ultrasonication probes that physically remove fouled material
- Application of "dynamic membranes" that rotate or vibrate to disrupt foulant

::: {.callout-important}
## UTP

A very successful technology that was developed several years ago is Uniform-Transmembrane Pressure (UTP).
The $TMP$ value we calculate is actually an average of the pressure on the feed side (pressure on feed and retenate):

$$TMP = \frac{P_{f} + P_{r}}{2}$$

There is a pressure drop $\Delta P$ from the feed to the retentate, while the pressure on the opposite (permeate) side
of the membrane is uniformly atmospheric.

This means that the $TMP$ at individual points of the membrane surface is variable.
Put simply: the TMP nearest the feed inlet is highest and that nearest the retentate outlet is lowest.

Consider that the "driving force" for separation in a filtration process is TMP.
The above situation means that a significant amount of the separation is happening
in a small proportion of the membrane area (near the feed inlet).

UTP is an effort to ensure that $TMP$ is approximately equal throughout the length of the membrane.
This can be achieved, for example, by recirculating the permeate on the permeate side of the membrane,
such that after permeate is collected it is pumped on the permeate side from a position corresponding
to the feed inlet (opposite side of membrane).
This creates a high pressure region at the permeate inlet that reduces $TMP$ at that point.
The pressure at the permeate outlet is still atmospheric pressure, meaning that the TMP
has only been reduced at the feed inlet, solving the problem of unequal TMP across the
membrane length.
:::


Examples of two recent developments in this area are briefly described below.

#### Charged membranes

Most membrane processes to concentrate or fractionate proteins are based on 
pores being small enougn to physically repel larger molecules.
By virtue of the molecules making physical contact with the membrane surface, however,
these molecules can become associated with fouling layers.

A recently-developed approach is to use larger pores that are activated with an electrostatic charge.
For example, in a feed containing negatively charged proteins of 10 kDa in size a membrane can be
selected with a MWCO of 100 kDa but that is modified to have a negative charge.

This system ensures that:

1. The proteins are repelled through electrostic forces
2. Fouling is mitigated by limiting protein-membrane contact
3. Membrane resistance is decreased due to the high MWCO
4. A high and sustainable permeate flux is created due to 1-3

Such charged membranes have been demonstrated to be successful at lab- and pilot-scale but have been adopted to a limited extent in the food industry to date.

#### Low-temperature processing

A somewhat counter-intuitive finding in recent years is that operating
filtration plants at close to refrigeration temperatures can have benefits for ensuring more sustainable flux values.

The mechanism behind this is unclear at this point but what is apparent is that sacrificing the high initial fluxes
associated with warm filtration can result in longer process runs, less down-time and reduced cleaning costs.
This sacrifice in initial productivity to ensure long-term productivity is analogous to operation at sub-critical flux.

It is not all good news, however, as larger pumps may be required to handle the more viscous feed material and there may also be associated refrigeration costs.
Nonetheless, several dairy companies have begun to transition to low-temperature processing.

## Appendix

### Streams

There are three streams to consider during any filtration process: the
feed, retentate and permeate.
During filtration the feed is separated into the
retentate and permeate.
In a benchtop process the retentate is commonly
recirculated back to the feed, which becomes increasingly concentrated over
time.

### Concentration factor

As permeate volume ($P_V$) increases the feed volume ($F_V$) decreases.
Typically there is a target volume concentration factor ($VCF$) that can be used to estimate the increase in protein content in the feed but also to set a limit on the process:

$$VCF = \frac{F_v}{F_v - P_v}$$

Hence, if you start with $1 \ L$ of feed, generate $670 \ mL$ of permeate you will have achieved a $VCF$ of $3×$.
If the starting protein concentration was
$3\%$ the concentration afterwards would be roughly $3 \ × \ 3 = 9$.
An efficient filtration process is one that has a high permeate flux that
is sustainable over time.
Flux is the flow-rate of permeate per unit of membrane area and typically has the units $L \ m^{−2} \ h^{−1}$.

::: {.callout-tip}

## Converting Flow Data

Consider that you have measured $10 \ mL$ of permeate in $30 \ seconds$ and the membrane area used was $0.1 \ m^2$:

**$mL$ to $L$** : 10 ÷ 1000 = 0.01

**$L \ 30s^{−1}$ to $L \ h^{−1}$** : 0.01 × 2 × 60 = 1.2

**$L h^{−1}$ to $L \ m^{−2} \ h^{−1}$** : 1.2 ÷ 0.1 = 12

The answer is:

$$12 \ L \ m^{-2} \ h^{-1}$$
:::

## Diafiltration

Diafiltration is simply a "washing" step.
It reduces the viscosity of the feed and improves filtration performance.

It is typically done in batch or continuous mode.
For example, batch diafiltration might involve removing 50% of feed volume of permeate, followed by replacing that volume in the feed with water, which is then subsequently removed again.

In practice, continuous diafiltration is more common as it is more effective in maintaining filtration performance.
This method involves continuously adding water to the feed at the same rate as which permeate is being removed.
At the end of the filtration process the water that has been added can then be removed.

