---
title: Mixing
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: false
---
---

## Foods as Complex Systems

Foods are *complex* in the sense that they consist of many parts related to each other in different ways (one thing might be *dispersed in* another thing, for example).
When food scientists refer to "food structure" they usually mean the totality of these relationships.
We do not need to go into detailed chemistry or physics to explore these structures.

Consider the three basic phases of matter: gas (G), liquid (L) and solid (S).
In a given food system each can be dispersed in the other.
When we say that a gas is *dispersed in* a solid we mean that the solid is continuous while the gas is present as discrete regions separate from each other (e.g., bubbles).
In abbreviated form we can represent this as G/S.

Now consider this table:

|   | G    | L    | S    |
|---|------|------|------|
| G | G/G  | L/G  | S/G  |
| L | G/L  | L/L  | S/L  |
| S | G/S  | L/S  | S/S  |

Each pair represents a structure, of particular interest are:

- G/L: liquid foam (e.g., beer froth)
- G/S: solid foam (e.g., bread)
- L/L: emulsion (e.g., milk)
- L/S: gel (e.g., yoghurt)
- S/G: powder (e.g., soy protein concentrate)
- S/L: liquid suspension (e.g., fruit juice with bits)
- S/S: solid suspension (e.g., chocolate)

There are important functional benefits to these various possible structures.
For example, the incorporation of air into a food can be effective at both reducing caloric density as well as material costs.
However, anecdotal evidence suggests that foaminess in a beverage is perceived positively or negatively depending on the region of the world in which it is consumed.

We have already spoken about emulsions at length.
It is easy to forget that the presence of both an oil and a water phase is necessary for the co-existence of oil- and water-soluble nutrients (as well as flavours).

Formulating foods involves combining the *right* ingredients at the *right* levels to form the *right* structure.
In most cases a formulated food will be mixed until the resultant mixture is "stable", although this does not necessarily mean that everything is dissolved.
The *wrong* structure here is one that stratifies quickly into different layers with different compositions.

Homogenisation — covered previously — is a high-shear process used to reduce already microscopic particles to close to sub-microscopic sizes.
"Mixing" typically refers to lower-intensity operations in which ingredients are combined (which may subsequently be homogenised).

## Ingredient Characteristics

While most food processes are *continuous*, many begin with a *batch* operation called mixing.
During this operation one or more powders are combined with a liquid phase.
The purpose of the operation is to promote the dissolution and/or dispersion of the powders.

How mixing proceeds depends to a great extent on the nature of the ingredients.
Consider the case of a formulated nutritional beverage, which might contain the following ingredients (at an absolute minimum!):

- **Sucrose**: soluble in water
- **Whey protein**: soluble in water but slightly hydrophobic
- **Calcium citrate**: insoluble in water (at non-acidic pH)
- **Potassium chloride**: soluble in water
- **Vitamins (various)**: soluble in water or oil
- **Vegetable oil**: immiscible in water

Sucrose is a dense crystalline structure that will sink quickly and dissolve.
Whey protein powders contain pockets or air and the hydrophobicity of the proteins tends to result in them floating at the liquid surface.
Calcium citrate will not dissolve in a milk-like product but will dissolve in a juice-like product.
It is therefore possible that at the end of a mixing process — depending on the product and ingredients — there may still be materials that are not fully dissolved.

Regardless of the exact nature of what is happening during mixing, the goal is typically to mix the ingredients as quickly and effectively as possible.
A prudent company will have at least one method to determine if the mixing has been effective; for example, if a product is supposed to have 10% protein but a sample of the mixture after a few minutes of ambient storage shows that it has 7% protein there may be a mixing problem that needs to be addressed.

::: {.callout-warning}

Mixing is an operation that is often *assumed* to be working when it may — in fact — not be working.

I have heard anecdotes where the level of a nutrient could vary by 45% across samples taken from a dry-mixed product.

:::

## Mixer Design

The design of a basic mixer is simple and consists of:

- An open vessel that allows ingredients to be added and the volume to be held
- A paddle attached to a shaft that can be rotated by a motor

In this section we will gradually add other components to this design to allow greater control.

Just like in the previous section, **turbulence** has an important role to play in promoting mixing.
The equation for turbulence in a mixer is very similar to what you have seen before; however, the motion is provided by the rotation of the paddle rather than the flow of a liquid through a pipe, which is reflected in the equation:

$$Re = \frac{D^{2} \cdot N \cdot \rho}{\mu}$$

Instead of $D$ representing the diameter of a pipe it represents the diameter of the paddle.
Instead of the velocity of liquid flow we have the number ($N$) of paddle rotations per second.

An effective mixing operation requires us to maximise the collisions that occur between particles and other particles, as well as particles and the equipment.
To do this we must maximise $Re$.

Once we have a specific paddle and a specific set of ingredients there is little that we can do to alter $D$ (assume we are stuck with the paddle the company bought) or $\rho$ (density is an intrinsic property of a liquid and varies little).

So we can increase $N$ by adjusting the speed of the motor and we can adjust $\mu$ by changing temperature.

To control temperature the mixing vessel needs to be jacketed, which allows warm water to be circulated in the walls of the vessel, thereby warming the mixture inside (to 40-60°C).

By increasing mixing speed and reducing mixture viscosity the mixing operation proceeds at a faster rate, at least in theory.

## Vortices and Baffles 

::: {.callout-tip}

These descriptions are far easier to understand with accompanying diagrams.

---

Such diagrams are provided in the lectures and it might be useful for you to connect them with the appropriate points in the notes.

:::

If you have ever mixed anything in a laboratory you are familiar the **vortex**.

You might even assume that a big vortex is evidence that things are mixing well.
This is — in fact — false.

The presence of a vortex if bad for two reasons:

1. It reduces the active volume inside the vessel
2. It is evidence of non-chaotic mixing (laminar)

A simple approach to solving this problem is to *break the vortex* using **baffles**.

If you create a vortex in a beaker and then submerge a pen in the vortex the vortex will disappear — this is because turbulence is created when liquid in motion encounters a static obstacle (this was observed/sketched by Leonardo Da Vinci and has been known for a very long time).

It is inconvenient (and unsanitary) for an operator to have to insert an object into the vessel so baffles are typically built in to the mixer design; hence, it is common to see baffles radiating from the inner walls of industrial mixers.

::: {.callout-important}

## Scaling Up

A common issue in product development is scale-up.

Let's say the product developers have made something interesting in a beaker.

The developers meet with the marketers and get excited about the concept, so they decide to plan a large production trial.

Even though *the exact same ingredients* are used the production run turns out to be a failure.
The idea might be abandoned at this point.

In such cases it is greatly important to ensure that the mixers at different scales are *as similar as possible*.

This notion of *similarity* is complex but can include things like:

- If the mixing is turbulent at lab-scale it needs to be turbulent at the larger scale also
- The ratio of the paddle diameter to the vessel diameter should be equivalent
- Temperatures and times should be equal
- Mixing pattern (axial/radial) should be equivalent

New ideas can be saved from the rubbish heap by ensuring consistency across scales (it's not just a matter of using the same ingredients).

:::

## Paddle Shape and Flow Pattern

If you mix some dye into a mixer you tend to observe two distinct patterns of mixing:

- Radial: side-to-side motion
- Axial: up-and-down motion

Specific mixer designs promote one over the other.

In general, the more aligned the paddle is with the vertical axis the more *radial* the mixing pattern, while the more slanted the paddle the more *axial* the mixing pattern.

Axial flow mixers tend to be preferred when there is a significant risk that particles will separate from the mixture (e.g., the sedimentation of calcium citrate).

Radial flow mixers often perform better in high viscosity products that require more shear; however, due to the hydrodynamics of their shape, they tend to require greater energy input to move through the liquid.

::: {.callout-important}

## Example of a Formulated Nutrition Product: Soylent

An interesting product case-study in formulated nutrition is [the meal-replacer Soylent](https://soylent.com/).
Soylent was initially developed by a software engineer — Rob Rhinehart — who ran a popular blog that described his experiments.
He wanted to create a beverage that would replace the requirement to shop for and prepare different meals every week.
His readers — many from Silicon Valley and with a similar focus on productivity and minimalism —  shared his vision for the meal-replacer.

Early prototypes of the product were largely assembled from powders sourced from Amazon that were then combined at levels to meet the nutritional requirements of an adult male (his case).
The product was further refined and Rhinehart successfully attracted (crowd)funding to build a Soylent business.
The path for Soylent has been rocky but it is now considering expanding outside its main market in North America (without Rhinehart as CEO).

I refer to Soylent as an "interesting" food product.
It's interesting for a variety of reasons:

- It was initially promoted as a complete meal-replacer (a rather ambitious and controversial claim)
- The name is taken from a 1970s Sci-Fi movie where "Soylent" is a protein-rich food that turns out to be made from people
- Its marketing focused on convenience (meal preparation is too labor-intensive), productivity (save time for what you really want to do) and sustainability (only drink what you need); the productivity focus is probably its most unique point of emphasis
- The concept attracted major criticism from (some) journalists and nutritional scientists when news of its development spread
- It is largely equivalent — in principle — to products that pre-date Soylent by many years (Abbott Ensure)
- The company repositioned itself recently to focus on "usage occasions" and expanded its range to include solid foods (the claim is no longer that the drink can replace all food)
- A significant proportion of its profits have historically been through e-commerce
- Two-thirds of their consumers are millenials or younger
- Its creator blogged extensively about its early development (some of these blogs are very thoughtful, especially when attempting to deal with the criticism)
- As a diet food it shares many problems with other meal-replacers (namely: taste fatigue)

In the end, the product consists mostly of a combination of ingredients that are mixed, heated and bottled.

The effectiveness of the mixing step is critical.

---

*References available on request.*

:::

## Dry Mixing

There is an example on Canvas of two ingredients being dry-mixed (poorly).
Dry-mixing is less well studied compared to wet-mixing and perhaps less common.
However, dry-mixing is practiced in the food industry (as well as the pharmaceutical industry).
The equipment used in dry-mixing and the underlying principles are quite different from wet-mixing, making it almost a separate field of study.

The primary issue associated with dry-mixing is **segregation**, where different ingredients tend to become concentrated in specific regions.
The reasons for segregation are complex, but usually arise when two ingredients have different sizes, shapes or densities.
In the preparation of a nutrient powder or pharmaceutical tablet segregation can lead to dramatically inconsistent compositions, which can be a major problem from an efficacy perspective.

## Other Uses of Mixing

The mixing describes here can be considered a kind of "formulation" (putting ingredients together to form a whole).

Mixing is not always used to combine ingredients, however; for example, lactose is often separated from the byproduct of whey protein concentrate manufacture ("whey permeate").
To concentrate the lactose so that it can be dried it must first be crytallised.
The crystallisation usually takes place in large mixing tanks with cooling jackets with very slow agitation to promote crystal growth.

Lactose manufactured by such processes is used in a variety of applications, from sweeteners to infant formula and pharmaceutical tablets.
